### PR TITLE
Added debian directory

### PR DESCRIPTION
**Pull request by umarbrowser**
The debian/ directory contains the source for building a debian package

### CODE REVIEW

**Comment by umarbrowser** [comment]
We have a lot to catch, Alot of errors

**Comment by umarbrowser** [comment]
Currently issues with tvb-framework are:
https://lintian.debian.org/tags/insane-line-length-in-source-file.html
https://lintian.debian.org/tags/source-contains-prebuilt-javascript-object.html
https://lintian.debian.org/tags/source-is-missing.html
https://lintian.debian.org/tags/duplicate-font-file.html
https://lintian.debian.org/tags/privacy-breach-generic.html
https://lintian.debian.org/tags/image-file-in-usr-lib.html

**Comment by umarbrowser** [comment]
Working to find the solutions

**Comment by liadomide** [comment]
Can you mark the js files from matjax, D3 and jquery to be ignored from check?

**Comment by umarbrowser** [comment]
Yes mentor i can working on it, i am putting the source is missing files to debian/missing-sources directory

**Comment by umarbrowser** [comment]
But showing the same error source-is-missing, here is another solution overriding lintian warning using `tvb-framework source: source-is-missing  ` on debian/source/lintian-overrides directory

**Comment by umarbrowser** [comment]
This is the last  source-is-missing error tvb/interfaces/web/static/mathjax/jax/output/SVG/fonts/TeX/Typewriter/Regular/Other.js and i check it exist in both .tar.gz and source directory i think overriding the source is the solution source-is-missing

**Pull request closed without merging**
